Feature/julio/newcooker
JulioSau/projectMcDonalds pull request #12
Opened 2020-08-28 08:49 UTC by JulioSau

2020-08-29 11:19 UTC, riduarte approved these changes

2020-09-14 10:40 UTC, JimenaEB requested changes

2020-09-14 10:40 UTC, JimenaEB commented on src/js/layout.js
> +/* import { Raiders } from "./views/viewRaiders"; */
Borrad comentarios

2020-09-14 10:40 UTC, JimenaEB commented on src/js/views/neworder.js
> +					<span className="total-minutes second-typography rounded">--------</span>
si es una linea lo que va a imprimir hazlo con css

2020-09-22 08:59 UTC, merged